# Generated by Django 2.0.1 on 2018-02-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default='request.user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_games', to='webapp.Profile'),
        ),
    ]
