# Generated by Django 2.0.1 on 2018-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
