# Generated by Django 2.0.1 on 2018-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_game_category'),
        ('webapp', '0002_auto_20180219_1432'),
    ]

    operations = [
    ]
