# Generated by Django 2.0.1 on 2018-02-26 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180226_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete='models.SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
    ]
