# Generated by Django 2.0.1 on 2018-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180219_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
