# Generated by Django 2.0.1 on 2018-02-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180210_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
