# Generated by Django 2.0.1 on 2018-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180210_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentReference',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
