# Generated by Django 2.0.1 on 2018-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
