# Generated by Django 2.0.1 on 2018-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_game_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.URLField(blank=True, default='static/img/NaN.png'),
        ),
    ]
