# Generated by Django 2.0.1 on 2018-02-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
