# Generated by Django 2.0.1 on 2018-02-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_order_paymentreference'),
        ('webapp', '0007_remove_profile_birth_date'),
    ]

    operations = [
    ]
