# Generated by Django 2.0.1 on 2018-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180224_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
