# Generated by Django 2.0.1 on 2018-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180224_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='logo',
        ),
    ]
