# Generated by Django 2.0.1 on 2018-02-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_merge_20180213_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='highscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Highscore',
        ),
    ]
