# Generated by Django 2.0.1 on 2018-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180214_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
