# Generated by Django 2.0.1 on 2018-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180217_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='score',
            field=models.IntegerField(blank=True, default='null', null=True),
        ),
    ]
