# Generated by Django 2.0.1 on 2018-02-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180217_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
