# Generated by Django 2.0.1 on 2018-02-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_profile_is_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highscores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_developer',
            new_name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='highscores',
        ),
        migrations.AddField(
            model_name='profile',
            name='developed_games',
            field=models.ManyToManyField(to='webapp.Game'),
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='_profile_games_+', to='webapp.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Profile'),
        ),
        migrations.AddField(
            model_name='highscores',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Game'),
        ),
        migrations.AddField(
            model_name='highscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Profile'),
        ),
    ]
