# Generated by Django 2.0.1 on 2018-02-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180206_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highscores',
            new_name='Highscore',
        ),
    ]
